### PR TITLE
Collapse arrow points to right when collapsed

### PR DESCRIPTION
**Pull request by jrbauti-09**

### CODE REVIEW

**Comment by jkettmann** [comment]
For some reason one of the Cypress tests fails from time to time. Unfortunately I wasn't able to fix this problem yet. That's why the CI pipeline failed. In this case you can simply click on the `Details` link and then re-run the jobs

grafik

**Comment by jkettmann** [comment]
And just in case you don't know you can get the PR approved by requesting a review from the bot
grafik

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-1)

**Comment by jrbauti-09** [comment]
Hi Johannes,

Thank you for reaching out to me with this issue. Do you know where I can
join your community group/ discord? I'm getting stumped on some of the
tasks.

Regards,

Joshua
ᐧ

**Comment by jkettmann** [comment]
Hi Joshua, you're welcome. Sorry for being so late with these comments. You can find the invite link to the community [here](https://profy.dev/project/react-job-simulator/welcome).

**Pull request merged**
